### ISSUE TITLE
Somehow a similar project, but a bit different

### ISSUE THREAD

**Issue by KOLANICH** [ihebski/DefaultCreds-cheat-sheet#1]
https://gist.github.com/KOLANICH/2d27d297c7f645428dc363d2f21380c5

The aim was not to collect credentials, but to collect some statistics on what threat actors insert backdoors the most frequently so to make data-driven consumer decisions.

But I haven't updated it for a while. Feel free to fork and continue the effort.

**Comment by ihebski** [comment]
Amazing idea.
Thanks a lot for sharing that.
