### ISSUE TITLE
Two other sources for default passwords

### ISSUE THREAD

**Issue by presianbg** [ihebski/DefaultCreds-cheat-sheet#10]
Hi,

You project is awesome.
Here are two other (a bit outdated) default password sources I use:

https://open-sez.me
https://cirt.net/passwords

Haven't checked if your collection covers them too. Sorry if so. 

Cheers!

**Comment by ihebski** [comment]
Thanks @presianbg for your contribution. :1st_place_medal: 

It seems like most of the devices were already covered in the project.
If you found an unlisted device feel free to send a pull request. 

Thank you,
Regards.
