### ISSUE TITLE
[Improvement] Default credentials for GLPI instances

### ISSUE THREAD

**Issue by doomerhunter** [ihebski/DefaultCreds-cheat-sheet#58]
Hi ! :)

GLPI is a quite frequent web service, especially within French companies. It's an IT Asset Management software with frequent vulnerabilities, either pre-auth or post-auth.

It can be common to find default credentials from the GLPI internal database on dev/prod instances on an internal network : 

Default login/passwords are:

- glpi / glpi
- tech tech
- normal / normal 
- post-only postonly 

Source : 
- [https://glpi-install.readthedocs.io/en/latest/install/wizard.html](https://glpi-install.readthedocs.io/en/latest/install/wizard.html)

**Comment by ihebski** [comment]
Hello @doomerhunter ,

That's a good idea, you can create a pull request for this one or if you like, I can make the changes.

Thank you

**Comment by ihebski** [comment]
Creds added to [dataset](https://github.com/ihebski/DefaultCreds-cheat-sheet/commit/b7ce824d854763a2895a2dde68d512e78e02c17d).
Thanks a lot @doomerhunter
