### ISSUE TITLE
error running defaultcreds 

### ISSUE THREAD

**Issue by Done461** [ihebski/DefaultCreds-cheat-sheet#59]
![image](https://github.com/ihebski/DefaultCreds-cheat-sheet/assets/52113967/fc88fc65-0ce0-4b06-be2c-534a5d17ca7b)

**Comment by ihebski** [comment]
Hello @Done461,

You have to install the dependencies in [requirements.txt](https://github.com/ihebski/DefaultCreds-cheat-sheet/blob/main/requirements.txt)

From the last screenshot,type `pip3 install tinydb==4.3` after that it should works properly.
