### ISSUE TITLE
default credentials for ICS & some common softwares

### ISSUE THREAD

**Issue by noraj** [ihebski/DefaultCreds-cheat-sheet#6]
Potential other sources of default credentials:

- https://github.com/arnaudsoullie/ics-default-passwords
- https://github.com/netbiosX/Default-Credentials

**Comment by ihebski** [comment]
Awesome, Thanks a lot for your contribution

**Comment by ihebski** [comment]
Hello @noraj ,

After reviewing the two links I have added the ICS passwords of https://github.com/arnaudsoullie/ics-default-passwords.
For the second link, it seems all covered on the dataset.

`README.md` sources were updated https://github.com/ihebski/DefaultCreds-cheat-sheet 

Thanks a lot for your contribution :1st_place_medal:

**Comment by noraj** [comment]
@ihebski Awesome, I'm about to public a tool based on your list.

**Comment by noraj** [comment]
> After reviewing the two links I have added the ICS passwords of https://github.com/arnaudsoullie/ics-default-passwords.

That introduced an error: https://github.com/ihebski/DefaultCreds-cheat-sheet/pull/7
