### ISSUE TITLE
[improvement] search using device MAC address

### ISSUE THREAD

**Issue by Albirew** [ihebski/DefaultCreds-cheat-sheet#67]
I don't know how much this can be feasible, but since we can get maker, and maybe device model using a MAC address, i wonder if it was possible to somehow link MAC address to default credentials...

Unfortunately, I cannot push any changes since i'm not much familiar with python, but i can at least give a MAC address database: https://maclookup.app/downloads/csv-database

**Comment by ihebski** [comment]
Hello @Albirew , I appreciate your suggestion. After reviewing the [XML file](https://maclookup.app/downloads/cisco-vendor-macs-xml-database/get-db?t=23-12-02&h=934d29bf3b091184a7dbf742e7bb7a6f92e9a8f1), I'm uncertain about the feasibility of inserting it into the credentials database. Nevertheless, we can explore an alternative approach by extracting the product name and conducting a search within creds script.

My next command might be able to assist you with that.

`cat vendorMacs.xml | grep "<MAC_ADDRESS_Here>" | grep -oP 'vendor_name="\K[^"]+' | xargs -I product_name sh -c 'creds search product_name'`

Exemple:
* we would like to search from this Mac address **CC:DE:DE**

`cat vendorMacs.xml | grep "CC:DE:DE" | grep -oP 'vendor_name="\K[^"]+' | xargs -I product_name sh -c 'creds search product_name'`
![search-mac](https://github.com/ihebski/DefaultCreds-cheat-sheet/assets/13177580/1a1c29e4-df52-4013-a7a4-b24d7402ff8e)

> It might fails if the product name does not precisely match the name in the database.

I hope you found this helpful.
