### ISSUE TITLE
Database file path in home

### ISSUE THREAD

**Issue by lap1nou** [ihebski/DefaultCreds-cheat-sheet#72]
Greetings,

First of all, thank you for this tool.

Do you think it would be possible to modify the creds database file location ? The current location is the main script location and it doesn't pair good with system such as `NixOS` where this location is marked as read only, wouldn't the home directory a better place maybe ?.

Regards.

**Comment by ihebski** [comment]
Hello @lap1nou ,

Thank you for flagging this issue. 
Currently, you can manually adjust the path to `path=/home/<USER>` under [Creds Script ligne 30](https://github.com/ihebski/DefaultCreds-cheat-sheet/blob/66a66395d019433dc3008fe5d79634abec6be5c9/creds#L30). In the future, we'll add an argument to simplify this process.

### Changes

Replace `path = pathlib.Path(__file__).parent` with `path = "/home/username"`

I hope this helps.
Regards

**Comment by lap1nou** [comment]
Hello @ihebski,

Thank you really much for the answer, no problem I will do that for the time being, I'm closing the issue then.

Regards.
